version: '3'

services:
  eass:
    build: ./docker/moodle
    image: eass_moodle
    environment:
      - IDE_KEY=eass-docker
      - SITE_DOMAIN=eass
      - LISTENING_PORT=80
    ports:
      - "80:80"
    volumes:
      - ./siteroot:/siteroot
    entrypoint: /entrypoint.sh

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: L0c4l_P4ssW0rd
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'db:/var/lib/postgresql'

  test-db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: L0c4l_P4ssW0rd
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes:
      - 'testdb:/var/lib/postgresql'

  behat-runner:
    depends_on:
      - eass
    build: ./docker/behat
    image: behat_runner
    environment:
      - IDE_KEY=behat-runner-docker
      - SITE_DOMAIN=behat-runner
      - LISTENING_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./siteroot:/siteroot
      - ./behatdata:/var/www/behatdata
      - ./behatfaildumps:/var/www/behatfaildumps
    entrypoint: /entrypoint.sh

  selenium:
    image: selenium/standalone-chrome-debug:latest
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900

volumes:
  db:
  testdb: